spring:
  application:
    name: hello-spring-cloud-web-admim-feign
  zipkin:
    base-url: http://localhost:9411
thymeleaf:
  cache: false
  mode: LEGACYHTML5
  encoding: UTF-8
  servlet:
    content-type: text/html


server:
  port: 8766

#开启自带熔断器
feign:
  hystrix:
    enabled: true


#注册到服务中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

